name = "jonji-api"
main = "src/index.ts"
compatibility_date = "2026-04-09"

[[d1_databases]]
binding = "DB"
database_name = "jonji-users"
database_id = "f66c433d-f649-4a4d-ae93-6b75b4817f6b"

[[kv_namespaces]]
binding = "KV"
id = "d33b3bfa51514e3b9cac2ca796cb60cb"

[[r2_buckets]]
binding = "R2"
bucket_name = "jonji-media"

[vars]
TINYBIRD_BASE_URL = "https://api.eu-central-1.aws.tinybird.co"
APP_URL = "https://jonji.me"
